#!/usr/bin/env bash
# Antigua's private network (run from the primary; safe to re-run). See README.md.
#
#   network/wg-mesh.sh                        install/refresh, guard enforcing
#   GUARD_MODE=observe network/wg-mesh.sh     guard only logs LAN hits
#
# Per host: wireguard-tools, a private key generated on the host (it never
# leaves), /etc/wireguard/wg0.conf peering with the other two, the nftables
# guard for that host's Antigua ports, and wg0 ordering drop-ins for the
# services that use the tunnel. Only the peers' /32s route over wg0 — no
# default route, no DNS — so the LAN, internet and AirPlay are untouched.
set -euo pipefail

GUARD_MODE=${GUARD_MODE:-enforce}
WG_PORT=51820
DIR=$(cd "$(dirname "$0")" && pwd)

case $GUARD_MODE in
    enforce) VERDICT=drop ;;
    observe) VERDICT=accept ;;
    *) echo "GUARD_MODE must be enforce or observe" >&2; exit 1 ;;
esac

# Host table: network/hosts.conf (git-ignored; template hosts.conf.example).
[ -f "$DIR/hosts.conf" ] || { echo "missing $DIR/hosts.conf — copy hosts.conf.example" >&2; exit 1; }
mapfile -t HOSTS < <(grep -Ev '^[[:space:]]*(#|$)' "$DIR/hosts.conf")

# Run the root shell script on stdin on a host.
on() {
    case $1 in
        local) sudo bash -s ;;
        root@*) ssh "$1" bash -s ;;
        *) ssh "$1" sudo bash -s ;;
    esac
}

declare -A PUB
for h in "${HOSTS[@]}"; do
    read -r name target _ <<<"$h"
    PUB[$name]=$(on "$target" <<'SH'
set -euo pipefail
command -v wg >/dev/null || DEBIAN_FRONTEND=noninteractive apt-get install -y -qq wireguard-tools >/dev/null
umask 077
mkdir -p /etc/wireguard
[ -s /etc/wireguard/wg0.key ] || wg genkey >/etc/wireguard/wg0.key
wg pubkey </etc/wireguard/wg0.key
SH
)
done

for h in "${HOSTS[@]}"; do
    read -r name target _ wg_ip ports units <<<"$h"

    conf="[Interface]
# $name — generated by Antigua network/wg-mesh.sh
Address = $wg_ip/24
ListenPort = $WG_PORT
PrivateKey = @PRIVATE_KEY@"
    for p in "${HOSTS[@]}"; do
        read -r pname _ plan pwg _ <<<"$p"
        [ "$pname" = "$name" ] && continue
        conf+="

[Peer]
# $pname
PublicKey = ${PUB[$pname]}
AllowedIPs = $pwg/32
Endpoint = $plan:$WG_PORT"
    done

    guard=$(sed -e "s/@PORTS@/${ports//,/, }/" -e "s/@VERDICT@/$VERDICT/" "$DIR/antigua-guard.nft")

    echo "── $name ($wg_ip): guard $GUARD_MODE on tcp $ports"
    on "$target" <<SH
set -euo pipefail
umask 077
cat >/etc/wireguard/wg0.conf <<'EOF_CONF'
$conf
EOF_CONF
sed -i "s|@PRIVATE_KEY@|\$(cat /etc/wireguard/wg0.key)|" /etc/wireguard/wg0.conf

umask 022
mkdir -p /etc/antigua
cat >/etc/antigua/guard.nft <<'EOF_NFT'
$guard
EOF_NFT
nft -c -f /etc/antigua/guard.nft
cat >/etc/systemd/system/antigua-guard.service <<'EOF_UNIT'
$(cat "$DIR/antigua-guard.service")
EOF_UNIT
for u in ${units//,/ }; do
    mkdir -p /etc/systemd/system/\$u.service.d
    cat >/etc/systemd/system/\$u.service.d/10-wireguard.conf <<'EOF_DROPIN'
$(cat "$DIR/10-wireguard.conf")
EOF_DROPIN
done
systemctl daemon-reload

if systemctl is-active -q wg-quick@wg0; then
    systemctl reload wg-quick@wg0
else
    systemctl enable -q --now wg-quick@wg0
fi
systemctl enable -q antigua-guard
systemctl restart antigua-guard
SH
done
