#!/usr/bin/env bash
# Deploy the failover stack to the backup box (run from the primary; safe to re-run).
#
#   antigua-fallback.service       server/antigua_fallback_server.py on :9394 —
#                                  idle (TTS-only box) until the primary is down
#   antigua-tts.service            kokoro_tts_server_flask.py on :5500 — backup TTS
#   kitchen-bridge-standby.service kitchen_bridge.py with standby_for_host —
#                                  takes the reSpeaker only while the primary is gone
#   server/mcp/venv, venv-atv      the Roku/Govee/Apple TV MCP servers the
#                                  fallback spawns on takeover (same pins)
#
# Mirrors the repo layout under $DEST so antigua_core's BASE_DIR resolves to
# $DEST and data/ lands in $DEST/data (memories/lists are kept in sync by
# root's crontab on the primary). Timers are deliberately not synced: both
# servers would fire them.
set -euo pipefail

REPO=$(cd "$(dirname "$0")/../.." && pwd)
# Hosts and paths live in the git-ignored deploy.env (template: deploy.env.example).
ENV_FILE="$REPO/server/scripts/deploy.env"
[ -f "$ENV_FILE" ] || { echo "missing $ENV_FILE — copy deploy.env.example and fill it in" >&2; exit 1; }
# shellcheck source=deploy.env.example
. "$ENV_FILE"
HOST=${FALLBACK_SSH:?set FALLBACK_SSH in deploy.env}
DEST=${FALLBACK_DIR:?set FALLBACK_DIR in deploy.env}
TTS_DIR=${FALLBACK_TTS_DIR:?set FALLBACK_TTS_DIR in deploy.env}
PRIMARY_IP=${PRIMARY_IP:?set PRIMARY_IP in deploy.env}
FALLBACK_WG_IP=${FALLBACK_WG_IP:?set FALLBACK_WG_IP in deploy.env}
RENDER="$REPO/venv/bin/python3 $REPO/server/scripts/render_unit.py --dir $DEST"

ssh "$HOST" "mkdir -p $DEST/server/config $DEST/server/mcp $DEST/kitchen-mic/bridge $DEST/data $DEST/logs"

rsync -az --delete --exclude __pycache__ "$REPO/server/antigua_core/" "$HOST:$DEST/server/antigua_core/"
rsync -az --delete "$REPO/server/static_audio/" "$HOST:$DEST/server/static_audio/"
rsync -az "$REPO/server/antigua_fallback_server.py" "$HOST:$DEST/server/"
rsync -az "$REPO/server/config/server.yaml" "$REPO/server/config/system_prompt.txt" "$HOST:$DEST/server/config/"
# MCP servers: pinned venv built on the box; secrets (GOVEE_API_KEY) copied
# from this machine's untracked mcp.env so the fallback can take over lights.
rsync -az "$REPO/server/mcp/requirements.txt" "$REPO/server/mcp/requirements-atv.txt" \
    "$REPO/server/mcp/setup.sh" "$HOST:$DEST/server/mcp/"
ssh "$HOST" "$DEST/server/mcp/setup.sh"
if [ -f "$REPO/server/config/mcp.env" ]; then
    rsync -az --chmod=F600 "$REPO/server/config/mcp.env" "$HOST:$DEST/server/config/"
else
    echo "warning: server/config/mcp.env missing — Govee will be LAN-only on the fallback" >&2
fi
# Apple TV pairing credentials: pairing is per client device ID stored in the
# file, so a copy lets the fallback control the Apple TV without re-pairing.
if [ -f "$REPO/server/config/pyatv.conf" ]; then
    rsync -az --chmod=F600 "$REPO/server/config/pyatv.conf" "$HOST:$DEST/server/config/"
else
    echo "warning: server/config/pyatv.conf missing — Apple TV unpaired on the fallback" >&2
fi
rsync -az "$REPO/kitchen-mic/bridge/kitchen_bridge.py" "$REPO/kitchen-mic/bridge/requirements.txt" \
    "$HOST:$DEST/kitchen-mic/bridge/"
rsync -az --ignore-existing "$REPO/data/memories.json" "$REPO/data/lists.json" "$HOST:$DEST/data/" 2>/dev/null || true

# Standby bridge config: the primary's (device PSK, MQTT, reply output),
# pointed at this box and told to stand by for the primary.
"$REPO/venv/bin/python3" - "$REPO/kitchen-mic/bridge/config.yaml" "$FALLBACK_WG_IP" "$PRIMARY_IP" <<'PY' \
    | ssh "$HOST" "cat > $DEST/kitchen-mic/bridge/config.yaml"
import sys, yaml
cfg = yaml.safe_load(open(sys.argv[1]))
me, primary = sys.argv[2], sys.argv[3]
cfg.update(
    run_on="backup (standby)",
    server_url="http://localhost:9394/pipeline",
    wake_cue_url=f"http://{me}:9394/audio/wake_cue.wav",
    standby_for_host=primary,
)
cfg.pop("fallback_server_url", None)
print("# Generated by server/scripts/deploy_fallback.sh — edit the primary's config.yaml instead.")
print(yaml.safe_dump(cfg, sort_keys=False), end="")
PY

# venvs (first run only; delete one to rebuild it)
ssh "$HOST" "[ -x $DEST/venv/bin/python3 ] || { python3 -m venv $DEST/venv && \
    $DEST/venv/bin/pip install -q faster-whisper feedparser num2words paho-mqtt requests PyYAML; }"
ssh "$HOST" "$DEST/venv/bin/python3 -c 'from faster_whisper import WhisperModel; WhisperModel(\"tiny\", device=\"cpu\", compute_type=\"int8\")'"
ssh "$HOST" "[ -x $DEST/kitchen-mic/bridge/venv/bin/python3 ] || { python3 -m venv $DEST/kitchen-mic/bridge/venv && \
    $DEST/kitchen-mic/bridge/venv/bin/pip install -q -r $DEST/kitchen-mic/bridge/requirements.txt; }"
# openWakeWord's models aren't in the wheel; copy the ones this box already has.
OWW=$("$REPO/kitchen-mic/bridge/venv/bin/python3" -c 'import openwakeword, os; print(os.path.dirname(openwakeword.__file__))')
RDIR=$(ssh "$HOST" "$DEST/kitchen-mic/bridge/venv/bin/python3 -c 'import openwakeword, os; print(os.path.dirname(openwakeword.__file__))'")
rsync -az "$OWW/resources/models/" "$HOST:$RDIR/resources/models/"

# Backup Kokoro TTS (antigua-tts.service, :5500) runs the primary's server script.
rsync -az "$REPO/server/kokoro_tts_server_flask.py" "$HOST:$TTS_DIR/tts_server.py"
ssh "$HOST" "systemctl restart antigua-tts"

# Units are rendered with @ANTIGUA_DIR@ = $DEST (server/scripts/render_unit.py).
for unit in server/antigua-fallback.service kitchen-mic/bridge/kitchen-bridge-standby.service \
        kitchen-mic/bridge/captures-prune.service kitchen-mic/bridge/captures-prune.timer; do
    $RENDER "$REPO/$unit" | ssh "$HOST" "cat > /etc/systemd/system/$(basename "$unit")"
done
# 7-day retention for what the standby bridge hears: captures and logs.
$RENDER "$REPO/server/antigua.logrotate" | ssh "$HOST" "cat > /etc/logrotate.d/antigua-fallback"
ssh "$HOST" "systemctl daemon-reload && systemctl enable -q --now captures-prune.timer && \
    systemctl enable -q antigua-fallback kitchen-bridge-standby && \
    systemctl restart antigua-fallback kitchen-bridge-standby && systemctl is-active antigua-fallback kitchen-bridge-standby"
